# Generated by Django 3.0.3 on 2020-05-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_alphabet', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D'), ('5', 'E'), ('6', 'F'), ('7', 'G'), ('8', 'H'), ('9', 'I'), ('10', 'J'), ('11', 'K'), ('12', 'L'), ('13', 'M'), ('14', 'N'), ('15', 'O'), ('16', 'P'), ('17', 'Q'), ('18', 'R'), ('19', 'S'), ('20', 'T'), ('21', 'U'), ('22', 'V'), ('23', 'W'), ('24', 'X'), ('25', 'Y'), ('26', 'Z'), ('27', 'AA'), ('28', 'AB'), ('29', 'AC'), ('30', 'AD')], max_length=2, verbose_name='列名(A)')),
            ],
        ),
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='色の系統')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='色番')),
                ('color_code', models.CharField(max_length=7, verbose_name='Hex')),
                ('index_number', models.CharField(max_length=2, verbose_name='列名(1)')),
                ('index_alphabet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colorpallet.ColorIndex', verbose_name='列名(A)')),
                ('type', models.ManyToManyField(to='colorpallet.ColorType', verbose_name='色の系統')),
            ],
        ),
    ]
