# Generated by Django 3.0.3 on 2020-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorpallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorindex',
            name='index_alphabet',
            field=models.CharField(max_length=2, verbose_name='列名(A)'),
        ),
    ]
